# syntax=docker/dockerfile:1
FROM rust:1.79 as builder
RUN cargo install trunk wasm-bindgen-cli --locked && rustup target add wasm32-unknown-unknown
WORKDIR /app
COPY frontend ./frontend
COPY Cargo.toml ./Cargo.toml
RUN trunk build --config frontend/Trunk.toml --dist /out

FROM nginx:alpine
COPY --from=builder /out /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
